Ensono/stacks-java

build/azDevops/azure/azure-pipelines-javaspring-k8s.yml, build/azDevops/azure/validate-yaml.yml, yamllint.conf
Adds a YAML Lint Pipeline and updates the build number counter to use the correct numbers.
Linting the YAML ensures yaml files (such as pipelines and K8s yamls) are at least correct YAML.
Adds a pipeline similar to the one on `stacks-webapp-template`
=> Adds Initial YAMLLint Pipeline

java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/builder/MenuBuilder.java
=> fixed menu Builder

java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/api/v1/menu/impl/MenuControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/service/MenuService.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/service/impl/MenuServiceImpl.java, java/src/main/resources/application.yml, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/v1/menu/impl/MenuControllerImplTest.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/v1/menu/matcher/TypeMatchers.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/util/TestHelper.java
=> SearchFilter removed code duplication

api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/CucumberTestSuite.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/category/CategoryActions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/item/ItemActions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/item/ItemRequests.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/menu/MenuActions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/menu/MenuRequests.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/models/Category.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/models/Item.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/CategoryStepDefinitions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/ItemStepDefinitions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/MenuStepDefinitions.java, api-tests/src/test/resources/features/category/CreateCategory.feature, api-tests/src/test/resources/features/item/CreateItem.feature, api-tests/src/test/resources/features/menu/GetAndSearchMenu.feature, api-tests/src/test/resources/features/menu/UpdateMenu.feature, api-tests/src/test/resources/templates/standard-item.properties
=> Add tests for 'Add Item' endpoint

api-tests/README.md, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/CucumberTestSuite.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/ExceptionMessages.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/category/CategoryRequests.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/item/ItemRequests.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/menu/MenuActions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/menu/MenuRequests.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/CategoryStepDefinitions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/Hooks.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/ItemStepDefinitions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/MenuStepDefinitions.java, api-tests/src/test/resources/features/category/CreateCategory.feature, api-tests/src/test/resources/features/category/DeleteCategory.feature, api-tests/src/test/resources/features/category/UpdateCategory.feature, api-tests/src/test/resources/features/item/CreateItem.feature, api-tests/src/test/resources/features/item/DeleteItem.feature, api-tests/src/test/resources/features/item/UpdateItem.feature, api-tests/src/test/resources/features/menu/CreateMenu.feature, api-tests/src/test/resources/features/menu/DeleteMenu.feature, api-tests/src/test/resources/features/menu/GetAndSearchMenu.feature, api-tests/src/test/resources/features/menu/UpdateMenu.feature, api-tests/src/test/resources/features/status/CheckApplicationStatus.feature
=> Add tests for 'Delete/Update Item' endpoint

api-tests/README.md, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/CucumberTestSuite.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/DeleteAllMenusCleanUp.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/menu/MenuRequests.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/models/Menu.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/models/ResponseWrapper.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/Hooks.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/ItemStepDefinitions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/MenuStepDefinitions.java, api-tests/src/test/resources/features/category/CreateCategory.feature, api-tests/src/test/resources/features/category/DeleteCategory.feature, api-tests/src/test/resources/features/category/UpdateCategory.feature, api-tests/src/test/resources/features/item/CreateItem.feature, api-tests/src/test/resources/features/item/DeleteItem.feature, api-tests/src/test/resources/features/item/UpdateItem.feature, api-tests/src/test/resources/features/menu/CreateMenu.feature, api-tests/src/test/resources/features/menu/DeleteAllMenusCleanUp.feature, api-tests/src/test/resources/features/menu/DeleteMenu.feature, api-tests/src/test/resources/features/menu/GetAndSearchMenu.feature, api-tests/src/test/resources/features/menu/UpdateMenu.feature
=> Add tests for 'DeleteAllMenus'

build/azDevops/azure/coverage/package-lock.json, build/azDevops/azure/coverage/package.json
Fixes the package lock problem.
Broken builds otherwise due to package URLs changing.
=> fix: Fixes gulp inlining and removes package

api-tests/pom.xml
=> Revert "build(deps): bump cucumber.version from 4.8.0 to 6.4.0 in /api-tests"

api-tests/pom.xml, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/menu/MenuRequests.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/pact/GenericMenuConsumer.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/pact/README.md, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/MenuStepDefinitions.java, api-tests/src/test/resources/features/category/UpdateCategory.feature, api-tests/src/test/resources/features/item/CreateItem.feature, api-tests/src/test/resources/features/item/DeleteItem.feature, api-tests/src/test/resources/features/item/UpdateItem.feature, api-tests/src/test/resources/features/menu/DeleteAllMenusCleanUp.feature, java/pom.xml
=> Add PACT contract tests

api-tests/pom.xml, build/azDevops/azure/azure-pipelines-javaspring-k8s.yml, build/azDevops/azure/templates/steps/build-api-tests.yml, build/azDevops/azure/templates/steps/build-java.yml, build/azDevops/azure/templates/steps/post-build-tasks.yml, java/pom.xml
Adds OWASP Vulnerability Checking to the build
=> feat: Adds OWASP Dependency Checker to the build

api-tests/pom.xml, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/pact/pacts/JavaAutomatedTestsMenuConsumer-JavaMenuAPI.json
=> Add PACT file and bump pom dependencies

api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/WebServiceEndPoints.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/MenuStepDefinitions.java, api-tests/src/test/resources/features/menu/GetAndSearchMenu.feature
=> Add tests for 'getMenuById - v2'

api-tests/README.md, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/ItemStepDefinitions.java, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/stepdefinitions/MenuStepDefinitions.java, api-tests/src/test/resources/features/category/CreateCategory.feature, api-tests/src/test/resources/features/category/DeleteCategory.feature, api-tests/src/test/resources/features/category/UpdateCategory.feature, api-tests/src/test/resources/features/item/CreateItem.feature, api-tests/src/test/resources/features/item/DeleteItem.feature, api-tests/src/test/resources/features/item/UpdateItem.feature, api-tests/src/test/resources/features/menu/CreateMenu.feature, api-tests/src/test/resources/features/status/CheckApplicationStatus.feature
=> Update the README file and check the typo errors

README.md
2355 - Updating ReadMe
Updated github readme
Added more information onto Github readMe
Notes for QA
=> 2355 - Updating ReadMe

build/azDevops/azure/azure-pipelines-javaspring-k8s.yml, build/jenkins/azure/jenkins-pipelines-javaspring-k8s.Jenkinsfile, java/Dockerfile
Also fixes Dockefile with `.m2` copied in.
=> fix: Adds a tag for the pipeline templates

api-tests/pom.xml, api-tests/src/test/resources/templates/category.json, api-tests/src/test/resources/templates/item.json, api-tests/src/test/resources/templates/menu.json
=> Bump to Cucumber5 version

api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/pact/README.md, api-tests/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/pact/pacts/JavaAutomatedTestsMenuConsumer-JavaMenuAPI.json, java/pom.xml
Fix Changed PACT configuration
=> Fix PACT configs

README.md
=> Cosmetic tweaks to README

.gitignore, api-tests-karate/README.md, api-tests-karate/logback-test.xml, api-tests-karate/pom.xml, api-tests-karate/src/test/java/CleanUpTestData.feature, api-tests-karate/src/test/java/CreateGenericData.feature, api-tests-karate/src/test/java/DeleteCreatedMenus.feature, api-tests-karate/src/test/java/GenerateOauthToken.feature, api-tests-karate/src/test/java/RunFunctionalTests.java, api-tests-karate/src/test/java/RunSmokeTests.java, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/category/CreateCategory.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/category/DeleteCategory.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/category/UpdateCategory.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/item/CreateItem.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/item/DeleteItem.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/item/UpdateItem.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/menu/CreateMenu.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/menu/DeleteMenu.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/menu/ReadApi.feature, api-tests-karate/src/test/java/com/xxAMIDOxx/xxSTACKSxx/api/karate/features/menu/UpdateMenu.feature, api-tests-karate/src/test/java/karate-config.js
=> Add Karate Tests

api-tests-karate/src/test/java/karate-config.js, build/azDevops/azure/azure-pipelines-javaspring-k8s.yml, build/jenkins/azure/jenkins-pipelines-javaspring-k8s.Jenkinsfile
Update API endpoint to `/api/menu`
Consistency with the .NET API
Notes for QA
=> chore: update api endpoint

java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/commands/CreateCategoryCommand.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/commands/CreateItemCommand.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/handlers/CreateCategoryHandler.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/handlers/CreateItemHandler.java
=> Updated generation and handling of categoryId and menuId

java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/CreateCategoryControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/CreateItemControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/CreateMenuControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/DeleteCategoryControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/DeleteItemControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/DeleteMenuControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/UpdateCategoryControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/UpdateItemControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/UpdateMenuControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/MenuQueryService.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/CategoryService.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/ItemService.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/MenuService.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/MenuServiceTest.java
[Java - Create non-CQRS Web Api App
Refactored how different events are created and published
Adding event creation in service will allow the controller to have less responsibilities and services to take care of it.
Each of the services have methods for create/update/delete event and then MenuService has the method to publish all these events
Please ensure Menu/Item/Category created/updated/deleted events are posted in Application insight
=> Refactoring event creation and publish

java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/CreateCategoryControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/CreateItemControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/CreateMenuControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/DeleteCategoryControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/DeleteItemControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/DeleteMenuControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/UpdateCategoryControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/UpdateItemControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/api/v1/impl/UpdateMenuControllerImpl.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/MenuQueryService.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/CategoryService.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/ItemService.java, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/MenuService.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/menu/domain/CategoryHelper.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/menu/domain/MenuHelper.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/CategoryServiceTest.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/ItemServiceTest.java, java/src/test/java/com/xxAMIDOxx/xxSTACKSxx/menu/service/impl/MenuServiceTest.java
2693 - Java - Create non-CQRS Web Api 
Adding unit tests for Service classes
Cover the functionality covered by the Service classes in unit tests
Created tests for all service class functionalities
Notes for QA
=> 2693 - Java - Create non-CQRS Web Api  App

build/azDevops/azure/azure-pipelines-javaspring-k8s.yml
=> chore: update for cli replacements

api-tests-karate/src/test/java/karate-config.js, api-tests/src/test/resources/serenity.conf, java/src/main/resources/auth.properties
Turned off Auth0 authentication
Notes for QA
=> Turning off auth0 no cqrs

api-tests-karate/src/test/java/karate-config.js, api-tests/src/test/resources/serenity.conf, java/src/main/resources/auth.properties
Turning off Auth0 authentication
Notes for QA
=> turning off auth0

java/pom.xml, java/src/main/resources/application.yml
Changed the Cosmos DB url to be Cosmos Emulator url by default
When people download this project or create this project using Scaffolding CLI they wouldn't have the cosmos db url used by the team.
Changed the cosmos db url in the application.yml file
Notes for QA
=> Removing Azure cosmos db url

api-tests/pom.xml
=> Remove the unused dependency

java/pom.xml, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/core/messaging/event/ApplicationEvent.java
=> fix(sec): Updating jackson-databind as suggested by dependabot

java/pom.xml, java/src/main/java/com/xxAMIDOxx/xxSTACKSxx/core/messaging/event/ApplicationEvent.java
=> fix(sec): Updating jackson-databind library

java/pom.xml, java/src/main/resources/application.yml
Updating spring boot starter parent
Dependabot suggested it
Notes for QA
=> fix(sec): Updating spring boot starter parent

api-tests/pom.xml, api-tests/src/test/resources/cucumber/features/item/CreateItem.feature, java/pom.xml
Updating libraries to latest versions
Keeping up to date
Notes for QA
=> fix: Updating versions of mockito, assertj-core and byte-buddy

api-tests-karate/pom.xml, api-tests/pom.xml, java/pom.xml
Bumping springboot versions
Keep libraries up to date
Notes for QA
=> fix: Bumping spring boot versions

build/azDevOps/azure/azure-pipelines-javaspring-k8s.yml, build/azDevOps/azure/azuredevops-vars.yml
📲 What
Move the top level variable out of the main pipeline file into a separate file.
AB#3595
🤔 Why
The Stacks CLI currently performs a search and replace on the template file to change the values based on the user input to the CLI. This is brittle because the original value could change and the CLI would not replace the value correctly.
By making this a separate file the CLI is able to build up the file as needed, without the need for any text replacements.
🛠 How
All of the variables are written to the variable template file, `azuredevops-vars.yaml`. This is included in the main build file, e.g.
```
variables:
template: azuredevops-vars.yml
```
👀 Evidence
The builds are working as before
🕵️ How to test
Notes for QA
✅ Acceptance criteria Checklist
Code peer reviewed?
Documentation has …
=> [3595] Use variable template for stacks-java

README.md
=> readme for cycle 6

api-tests-karate/pom.xml, api-tests/pom.xml, java/pom.xml, stackscli.yml
=> fix reduce chmod run only on !windows platforms

api-tests/pom.xml
fix: bump serenity maven plugins
Notes for QA
=> fix: includes reference to com.google.code.gson

java/src/main/java/com/amido/stacks/workloads/menu/domain/Category.java, java/src/main/java/com/amido/stacks/workloads/menu/domain/Menu.java, java/src/main/java/com/amido/stacks/workloads/menu/service/utility/MenuHelperService.java, java/src/main/java/com/amido/stacks/workloads/menu/service/v1/MenuService.java, java/src/main/java/com/amido/stacks/workloads/menu/service/v2/MenuServiceV2.java, java/src/test/java/com/amido/stacks/workloads/menu/api/v1/CategoryControllerTest.java, java/src/test/java/com/amido/stacks/workloads/menu/api/v1/ItemControllerTest.java, java/src/test/java/com/amido/stacks/workloads/menu/api/v1/MenuControllerTest.java, java/src/test/java/com/amido/stacks/workloads/menu/domain/MenuTest.java, java/src/test/java/com/amido/stacks/workloads/menu/service/utility/MenuHelperServiceTest.java
4750 - Remove Domain Behaviour on Entities
Refactor domain behaviour to service class
Better separation of concerns
See ADR
N/A
`mvn clean test`
=> Additional Refactoring

java/src/main/java/com/amido/stacks/workloads/menu/service/v1/SecretsService.java, java/src/main/resources/application.yml
Added support for Refresh via Actuator
To allow update of AWS Secrets
Notes for QA
=> Added support for Refresh via Actuator

build/azDevOps/azure/azure-pipelines-javaspring-k8s.yml, build/azDevOps/azure/azuredevops-vars.yml
Fixes for Production Deploy
Prod is broken
Notes for QA
=> fix: prod deploy

README.md, api-tests-karate/README.md, api-tests-karate/pom.xml, api-tests-karate/src/test/java/karate-config.js, api-tests/README.md, build/jenkins/azure/jenkins-pipelines-javaspring-k8s.Jenkinsfile
=> 409-Stacks: Upgrade Java modules

api-tests/pom.xml
Security Updates for August 2024
Updated dependencies to minor or patch versions to resolve vulnerabilities:
- logback (CVE-2023-6378)
- io.netty:netty-codec-http2 (No CVE)
- Jackson-databind (CVE-2022-42003, CVE-2021-46877, CVE-2022-42004)
- Netty's HttpPostRequestDecoder (CVE-2024-29025)
- JSON-JAVA (CVE-2023-5072, CVE-2022-45688)
Note: there is a update to Guava that appears to be breaking (based upon the major version number) will follow up with this after merged.
We are committed to resolving Critical, High and Medium vulnerabilities within a reasonable timeframe within Stacks to meet our obligations under ISO 27001, CyberEssentials Plus and numerous commitments to clients.
Manually merging in commits from dependabot so we have one long-running build rather than dozens of queued …
=> Security Updates 2024-08-15

build/azDevOps/azure/templates/steps/build/build-java.yml
=> fix: node to pwsh

api-tests/pom.xml, java/pom.xml
fix: more dep bumps
Notes for QA
=> fix: more dep bumps
